config/routes.rb
Rails.application.routes.draw do
  resources :authors

  resources :articles do
    resources :comments
  end
  resources :agendas

  resources :projects
  root :to => 'articles#index'
  #root 'articles#index'

end

app/models/agenda.rb
class Agenda
  include Mongoid::Document
  field :description, type: String
  field :priority, type: Integer
  field :solution, type: String
  field :status, type: String
  field :due, type: Date
end

app/controllers/agendas_controller.rb
class AgendasController < ApplicationController
  before_action :set_agenda, only: [:show, :edit, :update, :destroy]

  # GET /agendas
  # GET /agendas.json
  def index
    @agendas = Agenda.all
  end

  # GET /agendas/1
  # GET /agendas/1.json
  def show
  end

  # GET /agendas/new
  def new
    @agenda = Agenda.new
  end

  # GET /agendas/1/edit
  def edit
  end

  # POST /agendas
  # POST /agendas.json
  def create
    @agenda = Agenda.new(agenda_params)

    respond_to do |format|
      if @agenda.save
        format.html { redirect_to @agenda, notice: 'Agenda was successfully created.' }
        format.json { render :show, status: :created, location: @agenda }
      else
        format.html { render :new }
        format.json { render json: @agenda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agendas/1
  # PATCH/PUT /agendas/1.json
  def update
    respond_to do |format|
      if @agenda.update(agenda_params)
        format.html { redirect_to @agenda, notice: 'Agenda was successfully updated.' }
        format.json { render :show, status: :ok, location: @agenda }
      else
        format.html { render :edit }
        format.json { render json: @agenda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agendas/1
  # DELETE /agendas/1.json
  def destroy
    @agenda.destroy
    respond_to do |format|
      format.html { redirect_to agendas_url, notice: 'Agenda was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agenda
      @agenda = Agenda.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agenda_params
      params.require(:agenda).permit(:description, :priority, :solution, :status, :due)
    end
end

app/helpers/agendas_helper.rb
module AgendasHelper
end

app/views/agendas/_form.html.erb
<%= form_for(@agenda) do |f| %>
  <% if @agenda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agenda.errors.count, "error") %> prohibited this agenda from being saved:</h2>

      <ul>
      <% @agenda.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :priority %><br>
    <%= f.text_field :priority %>
  </div>
  <div class="field">
    <%= f.label :solution %><br>
    <%= f.text_field :solution %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :due %><br>
    <%= f.text_field :due %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/agendas/edit.html.erb
<h1>Editing Agenda</h1>

<%= render 'form' %>

<%= link_to 'Show', @agenda %> |
<%= link_to 'Back', agendas_path %>

app/views/agendas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Agendas</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Priority</th>
      <th>Solution</th>
      <th>Status</th>
      <th>Due</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agendas.each do |agenda| %>
      <tr>
        <td><%= agenda.description %></td>
        <td><%= agenda.priority %></td>
        <td><%= agenda.solution %></td>
        <td><%= agenda.status %></td>
        <td><%= agenda.due %></td>
        <td><%= link_to 'Show', agenda %></td>
        <td><%= link_to 'Edit', edit_agenda_path(agenda) %></td>
        <td><%= link_to 'Destroy', agenda, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Agenda', new_agenda_path %>

app/views/agendas/new.html.erb
<h1>New Agenda</h1>

<%= render 'form' %>

<%= link_to 'Back', agendas_path %>

app/views/agendas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @agenda.description %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @agenda.priority %>
</p>

<p>
  <strong>Solution:</strong>
  <%= @agenda.solution %>
</p>

<p>
  <strong>Status:</strong>
  <%= @agenda.status %>
</p>

<p>
  <strong>Due:</strong>
  <%= @agenda.due %>
</p>

<%= link_to 'Edit', edit_agenda_path(@agenda) %> |
<%= link_to 'Back', agendas_path %>